## (a) Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (Hint: create a 5x3 and 3x2 matrices and peform matrix multiplication).

In [1]:

import numpy as np
matrix1 = np.random.rand(5, 3)# Create random matrices
matrix2 = np.random.rand(3, 2)
result = np.dot(matrix1, matrix2)# Perform matrix multiplication
print(result)# Or matrix1 @ matrix2


[[0.56245373 0.38037932]
 [0.79562061 0.5182438 ]
 [1.20818244 0.77895126]
 [1.02445183 0.77758523]
 [1.27554857 1.06667774]]


## (b) Create a 3x3 identity matrix

In [2]:
matrix4 = np.eye(3,3)
print(matrix4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## (c) Create a vector with values ranging from 10 to 49).

In [3]:
vector = np.arange(10,49)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


## (d) Create a null vector of size 10.

In [4]:
nullVector = np.zeros(10)
print(nullVector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## (e) Create a 3x3x3 array with random values

In [5]:
matrix5 = np.random.rand(3,3,3)
print(matrix5)

[[[0.96213187 0.9590523  0.13635561]
  [0.7729774  0.37199774 0.81647528]
  [0.79922935 0.22937079 0.19994357]]

 [[0.82177859 0.57509867 0.25321125]
  [0.50629943 0.65943534 0.90463921]
  [0.6095671  0.84144727 0.20134978]]

 [[0.37492612 0.49171047 0.97704519]
  [0.42366723 0.69248576 0.51048398]
  [0.5125477  0.96462493 0.44377765]]]


## (f) Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [6]:
diagonal_matrix = np.diag([1, 2, 3, 4], k=-1)
print(diagonal_matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## (g) Normalize a 5x5 random matrix

In [8]:
matrix5 = np.random.rand(5,5,5)
normalized_matrix = (matrix5- matrix5.mean()) / matrix5.std() #subtract the mean and divide by the std
print(normalized_matrix)


[[[-0.1561977   1.22721971 -0.93212787  1.51169326 -1.48074079]
  [ 0.51448809 -0.94563298 -1.23274914 -0.8411085  -0.17841771]
  [ 0.65620591 -0.33892084 -1.15070301  1.33158787  1.7060718 ]
  [ 1.23117161  1.15407016  0.13697834  1.3926563  -1.40288721]
  [ 0.83700595  0.58331159 -0.04127799  1.0123551   1.58766479]]

 [[-0.92441795 -1.46277582 -0.72839931  1.39112578  0.9156536 ]
  [-0.91395086  1.18756969 -0.355201   -0.14669429 -0.72137103]
  [-1.04804845 -0.22590751 -1.09697426 -1.46015362  0.1025932 ]
  [-1.27842995  1.26411592  1.11972349 -1.43707566 -0.67278943]
  [ 1.68213224 -1.45930973 -0.84265163  0.95019706 -1.42975989]]

 [[ 0.52175444 -0.71545483  1.4145077   1.15441869  1.04194013]
  [-0.18211395 -0.22127862 -0.96425912 -0.7432044  -1.68886039]
  [ 1.5422495  -0.64889381 -1.37614205 -1.11497859  1.6765341 ]
  [-0.80188155  0.76295099  0.30849082 -1.29671531  0.20126802]
  [ 0.16233739 -0.25194431  0.86368876 -0.15172057  1.39928806]]

 [[-0.86232436 -0.49764817 -1.6715

## (h) How to get the dates of yesterday, today and tomorrow?

In [15]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2024-12-09
2024-12-10
2024-12-11


## (i) Find indices of non-zero elements from [1,2,0,0,4,0]. In all the above questions explain your approach.

In [16]:
array = np.array([1, 2, 0, 0, 4, 0])
non_zero_elements = np.nonzero(array)[0] # helps to find the indices of non-zero elements
print(non_zero_elements)


[0 1 4]
